### ISSUE TITLE
Candidate details 

### ISSUE THREAD

**Issue by alstorer** [camcycle/electionsurvey#27]
at the moment all candidate details have to be entered in a single copy and paste from a spreadsheet. Errors cannot be fixed by users easily. The only way is to correct the spreadsheet and re-enter everything. Pasting in partial new information deletes what was there

**Comment by mvl22** [comment]
Ref #14.

**Comment by mvl22** [comment]
An add candidate form was added in debf49d4cffbb305d6cfb0fa19847dd8ad8c665d.

An edit candidate form was added in e94ea301f86d4f7909bc644d6727c67f51ca25c9.
