### ISSUE TITLE
Control panel

### ISSUE THREAD

**Issue by davidearl** [camcycle/electionsurvey#9]
Would be very useful to have a control panel for managing all the admin things, like:
- setting up an election (import spreadsheet of candidates etc)
- search for and find candidate codes
- go to edit candidates' responses (e.g. for typos if requested)
- go to specific candidate data entry page
- sending proforma emails to remind candidates of their codes and where to go (with option to edit email content before sending).

**Comment by mvl22** [comment]
All these are now possible in the current admin area.
